### ISSUE TITLE
some error in tutorial: NASA MSL forebody _R,  reported from a freshman of Hystrath

### ISSUE THREAD

**Issue by pixingcai** [vincentcasseau/hyStrath#101] opened 2022-05-21 08:07 UTC
Hi  , Dr. Vincentcasseau , when I cd to hyStrath/hy2Foam/NASA_MSL_forebody/NASA_MSL_forebody_R, 
and execute : ./Allclean   ---->   ./Allrun,           some errors are reported and the case aborted,as following:
Illegal dictionary entry or environment variable name "Y_NO" Valid dictionary entries are 13(..............................)

Can you help me to figure it out ? thanks a lot

**Comment by vincentcasseau** [comment] 2022-05-21 08:22
Duplicate of #102

**Closed by vincentcasseau** 2022-05-21 08:22 UTC
