### ISSUE TITLE
install-DSMC compilation error

### ISSUE THREAD

**Issue by ARyakhovskiy** [vincentcasseau/hyStrath#13] opened 2019-03-10 09:31 UTC
Running ./install-DSMC.sh gives the following errors
[log.txt](https://github.com/vincentcasseau/hyStrath/files/2949271/log.txt)

:

1.)
/home/alexey/OpenFOAM/OpenFOAM-v1706/src/OpenFOAM/lnInclude/List.C:211:44: error: no matching function for call to ‘distance(int&, int&)’
     List<T>(begIter, endIter, std::distance(begIter, endIter))
      ...
2.)
/usr/include/c++/7/bits/stl_iterator_base_funcs.h:138:5: error: no type named ‘difference_type’ in ‘struct std::iterator_traits<int>’
make: *** [Make/linux64GccDPInt64Opt/parcels/dsmcParcel.o] Error 1
[1]+  Exit 2

**Comment by vincentcasseau** [comment] 2019-03-10 15:58
Hi Alexey,
I am tempted to say that you are missing some of the pre-requirements for OF-v1706. Please try this and let me know if there's any improvement.
`sudo apt-get install build-essential flex bison cmake zlib1g-dev libboost-system-dev libboost-thread-dev libopenmpi-dev openmpi-bin gnuplot libreadline-dev libncurses-dev libxt-dev`

**Comment by ARyakhovskiy** [comment] 2019-03-12 18:36
Hello,
No, I did have the essentials installed, running this string didn't install or upgrade anything. install-CFD runs successfully, but both DSMC and hybridPICDSMC finish with the same error.

**Comment by vincentcasseau** [comment] 2019-03-12 23:03
What is your Ubuntu version?
And gcc?
`gcc --version`

**Comment by ARyakhovskiy** [comment] 2019-03-13 04:52
Ubuntu 18.04.2
gcc 7.3.0

**Comment by ARyakhovskiy** [comment] 2019-03-26 14:01
The problem persists with Ubuntu 16.04 and gcc 5.4.0 20160609

**Comment by jimmyjohnh** [comment] 2019-03-28 21:09
Hey, 
I just tried installing it on my laptop with Ubuntu 14.04 and gcc 4.84 and I didn't get any issues

**Comment by peruni** [comment] 2019-07-23 23:19
I can confirm that there is an installation error of DSMC on 
OF v 1706, gcc 7.4.0, Ubuntu 18.04

**Comment by vincentcasseau** [comment] 2019-07-26 17:51
Hi Jakub, could you please contact me by email (see Wiki/People/Contact) and give me any info that you deem relevant (including install log, and full output of gcc -v). Thanks

**Comment by peruni** [comment] 2019-07-27 10:03
Hi Vincent,

I think I have very similar problem as Alexy.

I thought that the problem might be related to the g++ / gcc release so I have changed from 7 to 4.8 but I have the same problem. For now I believe that the problem is somehow related to the OF instalation but I haven't got time to figure it out.

Please find my loginstall attached to the email.


G++ is


g++ --version
g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Greetings from New Zealand!


----
Jakub Glowacki

Research Engineer

Robinson Research Institute

Faculty of Engineering | Te Wāhanga Ahunui Pūkaha

Victoria University of Wellington | Te Whare Wānanga o Te Ūpoko o te Ika a Māui

PO Box 5010 | Pouaka Poutāpeta 5010

Wellington | Te Whanganui-a-Tara

New Zealand | Aotearoa
Phone | Waea +64 4 463 0090

Email | Īmera jakub.glowacki@vuw.ac.nz<mailto:jakub.glowacki@vuw.ac.nz>



________________________________

**Comment by peruni** [comment] 2019-08-01 02:18
To all who has the same problem - I was able to solve it reinstalling OpenFoam from git repository here are the steps:
Download OpenFoam & ThirdParty
git clone https://develop.openfoam.com/Development/OpenFOAM-plus.git
wget https://downloads.sourceforge.net/project/openfoamplus/v1706/ThirdParty-v1706.tgz?r=http%3A%2F%2Fopenfoam.com%2Fcode%2Frepositories.php&ts=1502098894&use_mirror=vorboss
git checkout OpenFOAM-v1706
git fetch
git pull
compile Third Party
cgal_version=CGAL-4.9.1
boost_version=boost_1_64_0
compile OpenFoam
install hyStrath according to the instructions.

This approach worked in my case.

**Comment by vincentcasseau** [comment] 2019-08-10 18:25
Thanks for giving the solution to your problem and indeed confirming that it was not related to hyStrath. I am closing this issue.

**Comment by Ali19881366** [comment] 2021-05-11 10:03
Dear all

I faced the same error in ubuntu 20.04 when I want to compile the rheoTool package on OpenFOAM-7. 
However, I didn't the procedure suggested by @peruni because it is related to OpenFOAM v1706.
Do you know how to solve this problem?

Thanks

**Comment by peruni** [comment] 2021-05-11 22:14
Hi Ali, 
I have not tried to use OF-7 but I hardly doubt it will work. OF-1706 on the other hand has some outdated dependencies that you will not find on Ubuntu 20.04. My suggestion is to use a container build OF-1706 with the package.
I think more and more people will have this problem so maybe it would not be a bad idea to have a new repository with a container for future users. That would definitely be less troublesome that updating the whole package.

**Comment by Ali19881366** [comment] 2021-05-12 05:05
> Hi,
> What is rheoTool? In addition, OF-7 is not supported on this platform.
> Thanks,
> Vincent

Hello
This is a solver to solve the viscoelastic fluid flow in OpenFOAM.
https://github.com/fppimenta/rheoTool

**Comment by Ali19881366** [comment] 2021-05-12 05:09
> Hi Ali,
> I have not tried to use OF-7 but I doubt it will work with hyStrath. OF-1706 on the other hand has some outdated dependencies that you will not find on Ubuntu 20.04. My suggestion is to use a container with OF-1706 and the package.
> I think more and more people will have this problem so maybe it would not be a bad idea to have a new repository with a container for future users. That would definitely be less troublesome then updating the whole package.

Dear Peruni
Thanks for your reply.
But I need the 5th version of the rheoTool package and it just works on OF-7.
I had worked with its older version of rheoTool on an older version of OF. However, this is not working!
Thanks

**Comment by vincentcasseau** [comment] 2021-05-12 12:10
Then why don't you ask on their Github? or on cfd-online?

**Comment by ayush-s9** [comment] 2022-07-04 10:38
I was trying to implement the solution provided in this thread with regards to the compilation error for DSMC, but found that  https://downloads.sourceforge.net/project/openfoamplus/v1706/ThirdParty-v1706.tgz?r=http%3A%2F%2Fopenfoam.com%2Fcode%2Frepositories.php&ts=1502098894&use_mirror=vorboss has no files in it.
Is there some other way to solve the problem?

Thanks in advance

**Comment by vincentcasseau** [comment] 2022-07-04 12:09
Which versions of Ubuntu, OpenFOAM and gcc do you have?
- OpenFoam must be v1706
- If Ubuntu > 18.04-LTS, follow Step 1 on the Installation page

**Comment by ayush-s9** [comment] 2022-07-04 12:12
Thanks for the speedy reply
I have
Ubuntu 20.04 LTS
OpenFOAM-v1706 (I tried some of the tutorials for hy2Foam and my own cases as well, and it was running perfectly fine)
gcc and g++ version 7

**Comment by vincentcasseau** [comment] 2022-07-04 12:15
All good.
Could you please confirm that the DSMC installation log reported no errors?
What happens when you run the supersonic flat plate tuto?

**Comment by ayush-s9** [comment] 2022-07-04 12:18
That is where I'm having problem actually.
Both DSMC and pdFOAM have similar issues
[logInstall-DSMC.txt](https://github.com/vincentcasseau/hyStrath/files/9039328/logInstall-DSMC.txt)

**Comment by vincentcasseau** [comment] 2022-07-04 12:25
- Did you follow Step 1?
- Did you install all pre-requirements and double-check that all were successful?
- You said you had gcc 7, which subversion exactly (mine is 7.5)

I installed it last week on a Ubuntu 20.04 LTS VM and it worked fine.

**Comment by vincentcasseau** [comment] 2022-07-04 12:41
Thanks!
I found this post:
https://www.cfd-online.com/Forums/openfoam-installation/243122-custom-solver-twophaseflow-installation-error-openfoam-v1812.html

Yours is: ```-DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=64```
Mine is: ```-DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32```

I could either try to fix it for label size 64, or you could use label size 32. It depends how quickly you need it fixed.

**Comment by ayush-s9** [comment] 2022-07-04 12:49
Thanks for the response
I will try to use label size 32, but it'd be great if it works for label size 64.

Thanks again

**Comment by vincentcasseau** [comment] 2022-07-04 13:26
Please let me know when you can if the latest commit fixed all occurrences of this bug.
Thanks

**Comment by ayush-s9** [comment] 2022-07-04 16:03
DSMC is running now without any problems, I tried it for the supersonic flat plate tutorial.
pdFOAM still has the same issue during installation.
Please find attached the logInstall file for reference.
[logInstall-hybridPICDSMC.txt](https://github.com/vincentcasseau/hyStrath/files/9040880/logInstall-hybridPICDSMC.txt)

**Comment by vincentcasseau** [comment] 2022-07-04 16:38
Thanks for the feedback.
Locally, `int` type variables were still used. I changed all of these to OF's `label` type in the latest commit.
There shouldn't be a single `Label<int>` in the _lagrangian/_ folder anymore.

**Comment by ayush-s9** [comment] 2022-07-04 16:53
I don't think it has completely been resolved, since I got the same error again

**Comment by vincentcasseau** [comment] 2022-07-04 18:41
I missed a few in 0b62a33. I hope b509956 fixes it for good...

**Comment by ayush-s9** [comment] 2022-07-05 02:00
Yes, it is working without any problems now.
Thanks!

**Closed** 2022-07-05 07:07 UTC
Labels: question
